<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;
use App\Models\Category;

class ItemsTableSeeder extends Seeder
{
    /**
     * Auto-generated on 2025-08-29 06:58:39
     * Source: Form Peminjaman Alat - Master File - Copy.xlsx (sheet DB, headers: Kode Barang, Nama Barang, Serial Number, Tahun Pengadaan, Detail Barang)
     * Notes:
     * - TANPA JSON & TANPA NULL. Default: serial_number=SN-{code}, procurement_year=2025 (atau dari "TA-YYYY"), condition=baik, details fallback "Detail untuk {name}", category=Uncategorized.
     */
    public function run(): void
    {
        $rows = [
            [
                'code' => 'AV001',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112D40765084',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AV002',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112D40765152',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AV003',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112D40765087',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AV004',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112D40765052',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AV005',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112D40765110',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AV006',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112A56023122',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AV007',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112A56023154',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AV008',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112A56023132',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AV009',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112D40767101',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AV010',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112D40767085',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AV011',
                'name' => 'AV Matrix SDI to HDMI',
                'details' => 'Detail untuk AV Matrix SDI to HDMI',
                'serial_number' => '1112D40767071',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DCK001',
                'name' => 'Orico HDD/SSD Docking',
                'details' => 'Detail untuk Orico HDD/SSD Docking',
                'serial_number' => '24051765229',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'WL001',
                'name' => 'Working Lamp Sunrei C1500',
                'details' => 'Detail untuk Working Lamp Sunrei C1500',
                'serial_number' => 'SMG22D0381',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'WL002',
                'name' => 'Working Lamp Sunrei C1500',
                'details' => 'Detail untuk Working Lamp Sunrei C1500',
                'serial_number' => 'SMG22D0426',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BD001',
                'name' => 'B+D Smart Screwdriver',
                'details' => 'Detail untuk B+D Smart Screwdriver',
                'serial_number' => '5056174512554',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DP001',
                'name' => 'Thermaltake PSU Tester',
                'details' => 'Detail untuk Thermaltake PSU Tester',
                'serial_number' => 'AC069OO1NANA1ODCW00970',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD001',
                'name' => 'BMD SDI Distribution',
                'details' => 'Detail untuk BMD SDI Distribution',
                'serial_number' => '5707953',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD002',
                'name' => 'BMD UpDownCross ',
                'details' => 'Detail untuk BMD UpDownCross ',
                'serial_number' => '2400931',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD003',
                'name' => 'BMD UpDownCross ',
                'details' => 'Detail untuk BMD UpDownCross ',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD004',
                'name' => 'BMD UpDownCross ',
                'details' => 'Detail untuk BMD UpDownCross ',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD005',
                'name' => 'BMD UpDownCross ',
                'details' => 'Detail untuk BMD UpDownCross ',
                'serial_number' => '2400951',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD006',
                'name' => 'BMD Audio to SDI',
                'details' => 'Detail untuk BMD Audio to SDI',
                'serial_number' => '2123232',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD007',
                'name' => 'BMD SDI to Analog',
                'details' => 'Detail untuk BMD SDI to Analog',
                'serial_number' => '1550901',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD008',
                'name' => 'BMD HDMI to SDI',
                'details' => 'Detail untuk BMD HDMI to SDI',
                'serial_number' => '2384096',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD009',
                'name' => 'BMD DVI to SDI',
                'details' => 'Detail untuk BMD DVI to SDI',
                'serial_number' => '2205836',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD010',
                'name' => 'BMD SDI to Audio',
                'details' => 'Detail untuk BMD SDI to Audio',
                'serial_number' => '5706101',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD011',
                'name' => 'BMD UpDownCross ',
                'details' => 'Detail untuk BMD UpDownCross ',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD012',
                'name' => 'BMD Video Router 12x12',
                'details' => 'Detail untuk BMD Video Router 12x12',
                'serial_number' => '10510067',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD013',
                'name' => 'BMD Video Assist 7"',
                'details' => 'Detail untuk BMD Video Assist 7"',
                'serial_number' => '4677095',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD014',
                'name' => 'BMD Optic to SDI',
                'details' => 'Detail untuk BMD Optic to SDI',
                'serial_number' => '11067296',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD015',
                'name' => 'BMD Optic to SDI',
                'details' => 'Detail untuk BMD Optic to SDI',
                'serial_number' => '11067274',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD016',
                'name' => 'BMD Video Assist 7"',
                'details' => 'Detail untuk BMD Video Assist 7"',
                'serial_number' => '4677060',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BMD017',
                'name' => 'BMD SDI to Audio ',
                'details' => 'Detail untuk BMD SDI to Audio ',
                'serial_number' => '1539601',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AT001',
                'name' => 'ATEN Hdmi Splitter 4 Port',
                'details' => 'Detail untuk ATEN Hdmi Splitter 4 Port',
                'serial_number' => 'Z3LB0710340',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'VT001',
                'name' => 'Vention HDMI Splitter 4 Port',
                'details' => 'Detail untuk Vention HDMI Splitter 4 Port',
                'serial_number' => '-',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'VT002',
                'name' => 'Vention HDMI to RCA',
                'details' => 'Detail untuk Vention HDMI to RCA',
                'serial_number' => '-',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'VT003',
                'name' => 'Vention HDMI Splitter 4 Port',
                'details' => 'Detail untuk Vention HDMI Splitter 4 Port',
                'serial_number' => '-',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'VT004',
                'name' => 'Vention HDMI Splitter 4 Port',
                'details' => 'Detail untuk Vention HDMI Splitter 4 Port',
                'serial_number' => '-',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'SN001',
                'name' => 'Soliton Zao-X',
                'details' => 'Detail untuk Soliton Zao-X',
                'serial_number' => 'ZAO221128051',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'SN002',
                'name' => 'Soliton Zao-S',
                'details' => 'Detail untuk Soliton Zao-S',
                'serial_number' => '2001800',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'SN003',
                'name' => 'Soliton Zao-X',
                'details' => 'Detail untuk Soliton Zao-X',
                'serial_number' => 'ZAO221117038',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'LV001',
                'name' => 'Live U LU-300S',
                'details' => 'Detail untuk Live U LU-300S',
                'serial_number' => '3S2312-41512',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'LV002',
                'name' => 'Live U LU-300S',
                'details' => 'Detail untuk Live U LU-300S',
                'serial_number' => '3S2249-38246',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AJ001',
                'name' => 'AJA 3G HD Distribution Amplifier',
                'details' => 'Detail untuk AJA 3G HD Distribution Amplifier',
                'serial_number' => 'K0463224',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AJ002',
                'name' => 'AJA Pak Dock',
                'details' => 'Detail untuk AJA Pak Dock',
                'serial_number' => 'K0478976',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AJ003',
                'name' => 'AJA U-TAP SDI',
                'details' => 'Detail untuk AJA U-TAP SDI',
                'serial_number' => 'K0528729',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AJ004',
                'name' => 'AJA U-TAP SDI',
                'details' => 'Detail untuk AJA U-TAP SDI',
                'serial_number' => 'K0527644',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AJ005',
                'name' => 'AJA U-TAP SDI',
                'details' => 'Detail untuk AJA U-TAP SDI',
                'serial_number' => 'K0620858',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AJ006',
                'name' => 'AJA FIDO-TR',
                'details' => 'Detail untuk AJA FIDO-TR',
                'serial_number' => 'K0632806',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AJ007',
                'name' => 'AJA FIDO-TR',
                'details' => 'Detail untuk AJA FIDO-TR',
                'serial_number' => 'K0632807',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'TP001',
                'name' => 'TP-LINK Optic - LAN ',
                'details' => 'Detail untuk TP-LINK Optic - LAN ',
                'serial_number' => '22B1Q1001010',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'TP002',
                'name' => 'TP-LINK Optic - LAN',
                'details' => 'Detail untuk TP-LINK Optic - LAN',
                'serial_number' => '-',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DV001',
                'name' => 'Data Video VP-597 SDI Distribution',
                'details' => 'Detail untuk Data Video VP-597 SDI Distribution',
                'serial_number' => '00761539',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DV002',
                'name' => 'Data Video DAC-70 ',
                'details' => 'Detail untuk Data Video DAC-70 ',
                'serial_number' => '00724847',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DV003',
                'name' => 'Data Video DAC-70 ',
                'details' => 'Detail untuk Data Video DAC-70 ',
                'serial_number' => '00724846',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DV004',
                'name' => 'Data Video DAC-70 ',
                'details' => 'Detail untuk Data Video DAC-70 ',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DV005',
                'name' => 'Data Video DAC-70 ',
                'details' => 'Detail untuk Data Video DAC-70 ',
                'serial_number' => '00692026',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DV006',
                'name' => 'Data Video DAC-70 ',
                'details' => 'Detail untuk Data Video DAC-70 ',
                'serial_number' => '00773362',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DV007',
                'name' => 'Data Video DAC-70 ',
                'details' => 'Detail untuk Data Video DAC-70 ',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DV008',
                'name' => 'Data Video DAC-70 ',
                'details' => 'Detail untuk Data Video DAC-70 ',
                'serial_number' => '00700156',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'PX001',
                'name' => 'PX Wireless Presentation',
                'details' => 'Detail untuk PX Wireless Presentation',
                'serial_number' => '4717536602184',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'PX002',
                'name' => 'PX Wireless Presentation',
                'details' => 'Detail untuk PX Wireless Presentation',
                'serial_number' => '4717536602184',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AM001',
                'name' => 'Atomos Shogun 7" Monitor',
                'details' => 'Detail untuk Atomos Shogun 7" Monitor',
                'serial_number' => 'K1194SH750D55',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AM002',
                'name' => 'Atomos Docking SSD',
                'details' => 'Atomos SSD Docking Type-C',
                'serial_number' => 'K1294PHX00G70',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'FW001',
                'name' => 'Feel World 7" Monitor',
                'details' => 'Detail untuk Feel World 7" Monitor',
                'serial_number' => 'L7S35220767',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT001',
                'name' => 'Battery Pack Kingma 1960mAh',
                'details' => 'Detail untuk Battery Pack Kingma 1960mAh',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT002',
                'name' => 'Battery Pack Kingma 1960mAh',
                'details' => 'Detail untuk Battery Pack Kingma 1960mAh',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT003',
                'name' => 'Battery Pack Sony NP-F970',
                'details' => 'Battery Pack Sony NP-F970 6600mAh',
                'serial_number' => 'Y21ZG-1EK',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT004',
                'name' => 'Battery Pack Powerange DF-248',
                'details' => 'Battery Pack Powerange DF-248 6600mAh',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT005',
                'name' => 'Battery Pack VECT V-Mount',
                'details' => 'Battery Pack VECT V-Mount ET-130S 14,8V 130Wh',
                'serial_number' => 'YH160818PS20102',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT006',
                'name' => 'Battery Pack VECT V-Mount',
                'details' => 'Battery Pack VECT V-Mount ET-130S 14,8V 130Wh',
                'serial_number' => 'YH160818PS20170',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT007',
                'name' => 'Battery Pack NP-F970',
                'details' => 'Detail untuk Battery Pack NP-F970',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT008',
                'name' => 'Battery Pack NP-F970',
                'details' => 'Detail untuk Battery Pack NP-F970',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT009',
                'name' => 'Battery Pack NP-F970',
                'details' => 'Detail untuk Battery Pack NP-F970',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT010',
                'name' => 'Battery Pack CN-LP-E6',
                'details' => 'Detail untuk Battery Pack CN-LP-E6',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT011',
                'name' => 'Battery Pack CN-LP-E6',
                'details' => 'Detail untuk Battery Pack CN-LP-E6',
                'serial_number' => 'SN-BAT011',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'BAT012',
                'name' => 'Battery Pack SONY NP-F770',
                'details' => 'Detail untuk Battery Pack SONY NP-F770',
                'serial_number' => 'SN-BAT012',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'RF001',
                'name' => 'Sndway Laser Rangefinder',
                'details' => 'Detail untuk Sndway Laser Rangefinder',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'RF002',
                'name' => 'Sndway Laser Distance Meter',
                'details' => 'Sndway Laser Distance Meter H-D100A',
                'serial_number' => '230187507',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'RF003',
                'name' => 'Sndway Laser Distance Meter',
                'details' => 'Sndway Laser Distance Meter H-D100A',
                'serial_number' => '230026702',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'GP001',
                'name' => 'GoPro Hero 7',
                'details' => 'Detail untuk GoPro Hero 7',
                'serial_number' => 'C3261325694482',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'LI001',
                'name' => 'LITE LED Lighting',
                'details' => 'Detail untuk LITE LED Lighting',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AN001',
                'name' => 'AOKI UTX AT-6100 Antena Digital',
                'details' => 'Detail untuk AOKI UTX AT-6100 Antena Digital',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'SB001',
                'name' => 'STB POLITRON PDV 620T2',
                'details' => 'Detail untuk STB POLITRON PDV 620T2',
                'serial_number' => 'AOL423A12663',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'HD001',
                'name' => 'Hyper Drive MacBook Type-C Converter',
                'details' => 'Detail untuk Hyper Drive MacBook Type-C Converter',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'HD002',
                'name' => 'Hyper Drive MacBook Type-C Converter',
                'details' => 'Detail untuk Hyper Drive MacBook Type-C Converter',
                'serial_number' => '-',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'GC001',
                'name' => 'Google Chrome Cast 4K',
                'details' => 'Detail untuk Google Chrome Cast 4K',
                'serial_number' => '1C151HFDD4X1DB',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'MK001',
                'name' => 'Mikrotik Cloud Switch ',
                'details' => 'Mikrotik Cloud Switch CSS610-8G-2S+IN',
                'serial_number' => 'HDA08CC785M/242',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'MX001',
                'name' => 'MOXA Nport 5630 16 Port Switch',
                'details' => 'Detail untuk MOXA Nport 5630 16 Port Switch',
                'serial_number' => 'TAZF01027482',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'EA001',
                'name' => 'EVA-214 VGA EXTENDER',
                'details' => 'Detail untuk EVA-214 VGA EXTENDER',
                'serial_number' => 'V35000MK00090',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'EA002',
                'name' => 'EVA-214 VGA EXTENDER',
                'details' => 'Detail untuk EVA-214 VGA EXTENDER',
                'serial_number' => 'V37000MK00090',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'EA003',
                'name' => 'EVA-214 VGA EXTENDER',
                'details' => 'Detail untuk EVA-214 VGA EXTENDER',
                'serial_number' => 'V35000MK00081',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'EA004',
                'name' => 'EVA-214 VGA EXTENDER',
                'details' => 'Detail untuk EVA-214 VGA EXTENDER',
                'serial_number' => 'V37000MK00081',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'HL001',
                'name' => 'HOLLYLAND MARS T1000',
                'details' => 'Detail untuk HOLLYLAND MARS T1000',
                'serial_number' => '022251T1012159',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'HL002',
                'name' => 'HOLLYLAND MARS T1000',
                'details' => 'Detail untuk HOLLYLAND MARS T1000',
                'serial_number' => '022251T101215A',
                'procurement_year' => '2023',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'AP001',
                'name' => 'APUTURE AMARAN TRI-8C V-MOUNT',
                'details' => 'Detail untuk APUTURE AMARAN TRI-8C V-MOUNT',
                'serial_number' => '6BH00P88582',
                'procurement_year' => '-',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'DC001',
                'name' => 'DCK KDJF22 Reciprocating Saw',
                'details' => 'Detail untuk DCK KDJF22 Reciprocating Saw',
                'serial_number' => '612309003305',
                'procurement_year' => '2024',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'TL001',
                'name' => 'Lensa CANON HDTV Zoom Lens 40X',
                'details' => 'Detail untuk Lensa CANON HDTV Zoom Lens 40X',
                'serial_number' => '0032T763',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'MS001',
                'name' => 'Marshall CV506 HD Cam',
                'details' => 'Detail untuk Marshall CV506 HD Cam',
                'serial_number' => '15520501CD0582',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'SH001',
                'name' => 'SDI to HDMI Converter',
                'details' => 'Detail untuk SDI to HDMI Converter',
                'serial_number' => '160800000000000992',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'KR001',
                'name' => 'KRAMER VM-5HD 3G HD-SDI DA',
                'details' => 'Detail untuk KRAMER VM-5HD 3G HD-SDI DA',
                'serial_number' => '09121166500068',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'FL001',
                'name' => 'FLUKE 117 TRUE RMS MULTIMETER',
                'details' => 'Detail untuk FLUKE 117 TRUE RMS MULTIMETER',
                'serial_number' => '-',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'TL002',
                'name' => 'Lensa CANON HDTV Zoom Lens 40X',
                'details' => 'Detail untuk Lensa CANON HDTV Zoom Lens 40X',
                'serial_number' => '00610046',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ],
            [
                'code' => 'OPT001',
                'name' => 'OPTIC CABLE 300M - KUNING',
                'details' => 'Detail untuk OPTIC CABLE 300M - KUNING',
                'serial_number' => 'SN-OPT001',
                'procurement_year' => '2025',
                'condition' => 'baik',
                'category_name' => 'Uncategorized',
            ]
        ];

        foreach ($rows as $r) {
            // Safety fallback kedua
            $r['serial_number'] = $r['serial_number'] ?: ('SN-' . ($r['code'] ?: 'XXXX'));
            $r['procurement_year'] = $r['procurement_year'] ?: '2025';
            $r['details'] = $r['details'] ?: ('Detail untuk ' . ($r['name'] ?: $r['code']));
            $r['condition'] = $r['condition'] ?: 'baik';
            $catName = $r['category_name'] ?: 'Uncategorized';

            $codeCategory = strtoupper(preg_replace('/[^A-Z0-9]+/', '', $catName));
            if ($codeCategory === '') { $codeCategory = 'UNCAT'; }
            $codeCategory = substr($codeCategory, 0, 24);

            $category = Category::firstOrCreate(
                ['name' => $catName],
                ['code_category' => $codeCategory]
            );

            Item::create([
                'code'             => $r['code'],
                'name'             => $r['name'],
                'details'          => $r['details'],
                'serial_number'    => $r['serial_number'],
                'procurement_year' => $r['procurement_year'],
                'condition'        => $r['condition'],
                'category_id'      => $category->id,
            ]);
        }
    }
}
