-- UPSERT import (no TRUNCATE/DELETE). Updates/creates categories & items.
START TRANSACTION;

-- 1) Upsert categories (unique by name/code_category).
INSERT INTO `categories` (`name`,`code_category`,`created_at`,`updated_at`) VALUES
('AV Matrix SDI to HDMI', 'AVM', NOW(), NOW()),
('Orico HDD/SSD Docking', 'ORI', NOW(), NOW()),
('Working Lamp Sunrei C1500', 'WOR', NOW(), NOW()),
('B+D Smart Screwdriver', 'BDS', NOW(), NOW()),
('Thermaltake PSU Tester', 'THE', NOW(), NOW()),
('BMD SDI Distribution', 'BMD', NOW(), NOW()),
('BMD UpDownCross', 'BMB', NOW(), NOW()),
('BMD Audio to SDI', 'BMC', NOW(), NOW()),
('BMD SDI to Analog', 'BME', NOW(), NOW()),
('BMD HDMI to SDI', 'BMF', NOW(), NOW()),
('BMD DVI to SDI', 'BMG', NOW(), NOW()),
('BMD SDI to Audio', 'BMH', NOW(), NOW()),
('BMD Video Router 12x12', 'BMI', NOW(), NOW()),
('BMD Video Assist 7"', 'BMJ', NOW(), NOW()),
('BMD Optic to SDI', 'BMK', NOW(), NOW()),
('ATEN Hdmi Splitter 4 Port', 'ATE', NOW(), NOW()),
('Vention HDMI Splitter 4 Port', 'VEN', NOW(), NOW()),
('Vention HDMI to RCA', 'VEB', NOW(), NOW()),
('Soliton Zao-X', 'SOL', NOW(), NOW()),
('Soliton Zao-S', 'SOB', NOW(), NOW()),
('Live U LU-300S', 'LIV', NOW(), NOW()),
('AJA 3G HD Distribution Amplifier', 'AJA', NOW(), NOW()),
('AJA Pak Dock', 'AJB', NOW(), NOW()),
('AJA U-TAP SDI', 'AJC', NOW(), NOW()),
('AJA FIDO-TR', 'AJD', NOW(), NOW()),
('TP-LINK Optic - LAN', 'TPL', NOW(), NOW()),
('Data Video VP-597 SDI Distribution', 'DAT', NOW(), NOW()),
('Data Video DAC-70', 'DAB', NOW(), NOW()),
('PX Wireless Presentation', 'PXW', NOW(), NOW()),
('Atomos Shogun 7" Monitor', 'ATO', NOW(), NOW()),
('Atomos Docking SSD', 'ATB', NOW(), NOW()),
('Feel World 7" Monitor', 'FEE', NOW(), NOW()),
('Battery Pack Kingma 1960mAh', 'BAT', NOW(), NOW()),
('Battery Pack Sony NP-F970', 'BAB', NOW(), NOW()),
('Battery Pack Powerange DF-248', 'BAC', NOW(), NOW()),
('Battery Pack VECT V-Mount', 'BAD', NOW(), NOW()),
('Battery Pack NP-F970', 'BAE', NOW(), NOW()),
('Battery Pack CN-LP-E6', 'BAF', NOW(), NOW()),
('Battery Pack SONY NP-F770', 'BAG', NOW(), NOW()),
('Sndway Laser Rangefinder', 'SND', NOW(), NOW()),
('Sndway Laser Distance Meter', 'SNB', NOW(), NOW()),
('GoPro Hero 7', 'GOP', NOW(), NOW()),
('LITE LED Lighting', 'LIT', NOW(), NOW()),
('AOKI UTX AT-6100 Antena Digital', 'AOK', NOW(), NOW()),
('STB POLITRON PDV 620T2', 'STB', NOW(), NOW()),
('Hyper Drive MacBook Type-C Converter', 'HYP', NOW(), NOW()),
('Google Chrome Cast 4K', 'GOO', NOW(), NOW()),
('Mikrotik Cloud Switch', 'MIK', NOW(), NOW()),
('MOXA Nport 5630 16 Port Switch', 'MOX', NOW(), NOW()),
('EVA-214 VGA EXTENDER', 'EVA', NOW(), NOW()),
('HOLLYLAND MARS T1000', 'HOL', NOW(), NOW()),
('APUTURE AMARAN TRI-8C V-MOUNT', 'APU', NOW(), NOW()),
('DCK KDJF22 Reciprocating Saw', 'DCK', NOW(), NOW()),
('Lensa CANON HDTV Zoom Lens 40X', 'LEN', NOW(), NOW()),
('Marshall CV506 HD Cam', 'MAR', NOW(), NOW()),
('SDI to HDMI Converter', 'SDI', NOW(), NOW()),
('KRAMER VM-5HD 3G HD-SDI DA', 'KRA', NOW(), NOW()),
('FLUKE 117 TRUE RMS MULTIMETER', 'FLU', NOW(), NOW()),
('OPTIC CABLE 300M - KUNING', 'OPT', NOW(), NOW())
ON DUPLICATE KEY UPDATE `code_category`=VALUES(`code_category`), `updated_at`=VALUES(`updated_at`);

-- 2) Upsert items, binding category_id via category name.
/* Items upsert begin */
INSERT INTO `items` (`code`,`name`,`details`,`serial_number`,`procurement_year`,`condition`,`category_id`,`created_at`,`updated_at`) VALUES
('AV001','AV Matrix SDI to HDMI',NULL,'1112D40765084',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('AV002','AV Matrix SDI to HDMI',NULL,'1112D40765152',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('AV003','AV Matrix SDI to HDMI',NULL,'1112D40765087',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('AV004','AV Matrix SDI to HDMI',NULL,'1112D40765052',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('AV005','AV Matrix SDI to HDMI',NULL,'1112D40765110',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('AV006','AV Matrix SDI to HDMI',NULL,'1112A56023122',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('AV007','AV Matrix SDI to HDMI',NULL,'1112A56023154',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('AV008','AV Matrix SDI to HDMI',NULL,'1112A56023132',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('AV009','AV Matrix SDI to HDMI',NULL,'1112D40767101',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('AV010','AV Matrix SDI to HDMI',NULL,'1112D40767085',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('AV011','AV Matrix SDI to HDMI',NULL,'1112D40767071',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='AV Matrix SDI to HDMI' LIMIT 1),NOW(),NOW()),
('DCK001','Orico HDD/SSD Docking',NULL,'24051765229',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='Orico HDD/SSD Docking' LIMIT 1),NOW(),NOW()),
('WL001','Working Lamp Sunrei C1500',NULL,'SMG22D0381',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='Working Lamp Sunrei C1500' LIMIT 1),NOW(),NOW()),
('WL002','Working Lamp Sunrei C1500',NULL,'SMG22D0426',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='Working Lamp Sunrei C1500' LIMIT 1),NOW(),NOW()),
('BD001','B+D Smart Screwdriver',NULL,'5056174512554',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='B+D Smart Screwdriver' LIMIT 1),NOW(),NOW()),
('DP001','Thermaltake PSU Tester',NULL,'AC069OO1NANA1ODCW00970',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='Thermaltake PSU Tester' LIMIT 1),NOW(),NOW()),
('BMD001','BMD SDI Distribution',NULL,'5707953',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD SDI Distribution' LIMIT 1),NOW(),NOW()),
('BMD002','BMD UpDownCross',NULL,'2400931',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD UpDownCross' LIMIT 1),NOW(),NOW()),
('BMD003','BMD UpDownCross',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD UpDownCross' LIMIT 1),NOW(),NOW()),
('BMD004','BMD UpDownCross',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD UpDownCross' LIMIT 1),NOW(),NOW()),
('BMD005','BMD UpDownCross',NULL,'2400951',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD UpDownCross' LIMIT 1),NOW(),NOW()),
('BMD006','BMD Audio to SDI',NULL,'2123232',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD Audio to SDI' LIMIT 1),NOW(),NOW()),
('BMD007','BMD SDI to Analog',NULL,'1550901',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD SDI to Analog' LIMIT 1),NOW(),NOW()),
('BMD008','BMD HDMI to SDI',NULL,'2384096',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD HDMI to SDI' LIMIT 1),NOW(),NOW()),
('BMD009','BMD DVI to SDI',NULL,'2205836',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD DVI to SDI' LIMIT 1),NOW(),NOW()),
('BMD010','BMD SDI to Audio',NULL,'5706101',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD SDI to Audio' LIMIT 1),NOW(),NOW()),
('BMD011','BMD UpDownCross',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD UpDownCross' LIMIT 1),NOW(),NOW()),
('BMD012','BMD Video Router 12x12',NULL,'10510067',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD Video Router 12x12' LIMIT 1),NOW(),NOW()),
('BMD013','BMD Video Assist 7"',NULL,'4677095',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD Video Assist 7"' LIMIT 1),NOW(),NOW()),
('BMD014','BMD Optic to SDI',NULL,'11067296',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD Optic to SDI' LIMIT 1),NOW(),NOW()),
('BMD015','BMD Optic to SDI',NULL,'11067274',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD Optic to SDI' LIMIT 1),NOW(),NOW()),
('BMD016','BMD Video Assist 7"',NULL,'4677060',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD Video Assist 7"' LIMIT 1),NOW(),NOW()),
('BMD017','BMD SDI to Audio',NULL,'1539601',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='BMD SDI to Audio' LIMIT 1),NOW(),NOW()),
('AT001','ATEN Hdmi Splitter 4 Port',NULL,'Z3LB0710340',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='ATEN Hdmi Splitter 4 Port' LIMIT 1),NOW(),NOW()),
('VT001','Vention HDMI Splitter 4 Port',NULL,'-',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='Vention HDMI Splitter 4 Port' LIMIT 1),NOW(),NOW()),
('VT002','Vention HDMI to RCA',NULL,'-',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='Vention HDMI to RCA' LIMIT 1),NOW(),NOW()),
('VT003','Vention HDMI Splitter 4 Port',NULL,'-',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='Vention HDMI Splitter 4 Port' LIMIT 1),NOW(),NOW()),
('VT004','Vention HDMI Splitter 4 Port',NULL,'-',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='Vention HDMI Splitter 4 Port' LIMIT 1),NOW(),NOW()),
('SN001','Soliton Zao-X',NULL,'ZAO221128051',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='Soliton Zao-X' LIMIT 1),NOW(),NOW()),
('SN002','Soliton Zao-S',NULL,'2001800',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Soliton Zao-S' LIMIT 1),NOW(),NOW()),
('SN003','Soliton Zao-X',NULL,'ZAO221117038',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Soliton Zao-X' LIMIT 1),NOW(),NOW()),
('LV001','Live U LU-300S',NULL,'3S2312-41512',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='Live U LU-300S' LIMIT 1),NOW(),NOW()),
('LV002','Live U LU-300S',NULL,'3S2249-38246',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='Live U LU-300S' LIMIT 1),NOW(),NOW()),
('AJ001','AJA 3G HD Distribution Amplifier',NULL,'K0463224',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='AJA 3G HD Distribution Amplifier' LIMIT 1),NOW(),NOW()),
('AJ002','AJA Pak Dock',NULL,'K0478976',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='AJA Pak Dock' LIMIT 1),NOW(),NOW()),
('AJ003','AJA U-TAP SDI',NULL,'K0528729',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='AJA U-TAP SDI' LIMIT 1),NOW(),NOW()),
('AJ004','AJA U-TAP SDI',NULL,'K0527644',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='AJA U-TAP SDI' LIMIT 1),NOW(),NOW()),
('AJ005','AJA U-TAP SDI',NULL,'K0620858',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='AJA U-TAP SDI' LIMIT 1),NOW(),NOW()),
('AJ006','AJA FIDO-TR',NULL,'K0632806',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='AJA FIDO-TR' LIMIT 1),NOW(),NOW()),
('AJ007','AJA FIDO-TR',NULL,'K0632807',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='AJA FIDO-TR' LIMIT 1),NOW(),NOW()),
('TP001','TP-LINK Optic - LAN',NULL,'22B1Q1001010',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='TP-LINK Optic - LAN' LIMIT 1),NOW(),NOW()),
('TP002','TP-LINK Optic - LAN',NULL,'-',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='TP-LINK Optic - LAN' LIMIT 1),NOW(),NOW()),
('DV001','Data Video VP-597 SDI Distribution',NULL,'00761539',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Data Video VP-597 SDI Distribution' LIMIT 1),NOW(),NOW()),
('DV002','Data Video DAC-70',NULL,'00724847',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Data Video DAC-70' LIMIT 1),NOW(),NOW()),
('DV003','Data Video DAC-70',NULL,'00724846',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Data Video DAC-70' LIMIT 1),NOW(),NOW()),
('DV004','Data Video DAC-70',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Data Video DAC-70' LIMIT 1),NOW(),NOW()),
('DV005','Data Video DAC-70',NULL,'00692026',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Data Video DAC-70' LIMIT 1),NOW(),NOW()),
('DV006','Data Video DAC-70',NULL,'00773362',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Data Video DAC-70' LIMIT 1),NOW(),NOW()),
('DV007','Data Video DAC-70',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Data Video DAC-70' LIMIT 1),NOW(),NOW()),
('DV008','Data Video DAC-70',NULL,'00700156',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Data Video DAC-70' LIMIT 1),NOW(),NOW()),
('PX001','PX Wireless Presentation',NULL,'4717536602184',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='PX Wireless Presentation' LIMIT 1),NOW(),NOW()),
('PX002','PX Wireless Presentation',NULL,'4717536602184',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='PX Wireless Presentation' LIMIT 1),NOW(),NOW()),
('AM001','Atomos Shogun 7" Monitor',NULL,'K1194SH750D55',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Atomos Shogun 7" Monitor' LIMIT 1),NOW(),NOW()),
('AM002','Atomos Docking SSD','Atomos SSD Docking Type-C','K1294PHX00G70',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Atomos Docking SSD' LIMIT 1),NOW(),NOW()),
('FW001','Feel World 7" Monitor',NULL,'L7S35220767',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Feel World 7" Monitor' LIMIT 1),NOW(),NOW()),
('BAT001','Battery Pack Kingma 1960mAh',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack Kingma 1960mAh' LIMIT 1),NOW(),NOW()),
('BAT002','Battery Pack Kingma 1960mAh',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack Kingma 1960mAh' LIMIT 1),NOW(),NOW()),
('BAT003','Battery Pack Sony NP-F970','Battery Pack Sony NP-F970 6600mAh','Y21ZG-1EK',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack Sony NP-F970' LIMIT 1),NOW(),NOW()),
('BAT004','Battery Pack Powerange DF-248','Battery Pack Powerange DF-248 6600mAh','-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack Powerange DF-248' LIMIT 1),NOW(),NOW()),
('BAT005','Battery Pack VECT V-Mount','Battery Pack VECT V-Mount ET-130S 14,8V 130Wh','YH160818PS20102',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack VECT V-Mount' LIMIT 1),NOW(),NOW()),
('BAT006','Battery Pack VECT V-Mount','Battery Pack VECT V-Mount ET-130S 14,8V 130Wh','YH160818PS20170',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack VECT V-Mount' LIMIT 1),NOW(),NOW()),
('BAT007','Battery Pack NP-F970',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack NP-F970' LIMIT 1),NOW(),NOW()),
('BAT008','Battery Pack NP-F970',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack NP-F970' LIMIT 1),NOW(),NOW()),
('BAT009','Battery Pack NP-F970',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack NP-F970' LIMIT 1),NOW(),NOW()),
('BAT010','Battery Pack CN-LP-E6',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack CN-LP-E6' LIMIT 1),NOW(),NOW()),
('BAT011','Battery Pack CN-LP-E6',NULL,NULL,NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack CN-LP-E6' LIMIT 1),NOW(),NOW()),
('BAT012','Battery Pack SONY NP-F770',NULL,NULL,NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Battery Pack SONY NP-F770' LIMIT 1),NOW(),NOW()),
('RF001','Sndway Laser Rangefinder',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Sndway Laser Rangefinder' LIMIT 1),NOW(),NOW()),
('RF002','Sndway Laser Distance Meter','Sndway Laser Distance Meter H-D100A','230187507',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='Sndway Laser Distance Meter' LIMIT 1),NOW(),NOW()),
('RF003','Sndway Laser Distance Meter','Sndway Laser Distance Meter H-D100A','230026702',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Sndway Laser Distance Meter' LIMIT 1),NOW(),NOW()),
('GP001','GoPro Hero 7',NULL,'C3261325694482',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='GoPro Hero 7' LIMIT 1),NOW(),NOW()),
('LI001','LITE LED Lighting',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='LITE LED Lighting' LIMIT 1),NOW(),NOW()),
('AN001','AOKI UTX AT-6100 Antena Digital',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='AOKI UTX AT-6100 Antena Digital' LIMIT 1),NOW(),NOW()),
('SB001','STB POLITRON PDV 620T2',NULL,'AOL423A12663',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='STB POLITRON PDV 620T2' LIMIT 1),NOW(),NOW()),
('HD001','Hyper Drive MacBook Type-C Converter',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Hyper Drive MacBook Type-C Converter' LIMIT 1),NOW(),NOW()),
('HD002','Hyper Drive MacBook Type-C Converter',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Hyper Drive MacBook Type-C Converter' LIMIT 1),NOW(),NOW()),
('GC001','Google Chrome Cast 4K',NULL,'1C151HFDD4X1DB',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='Google Chrome Cast 4K' LIMIT 1),NOW(),NOW()),
('MK001','Mikrotik Cloud Switch','Mikrotik Cloud Switch CSS610-8G-2S+IN','HDA08CC785M/242',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='Mikrotik Cloud Switch' LIMIT 1),NOW(),NOW()),
('MX001','MOXA Nport 5630 16 Port Switch',NULL,'TAZF01027482',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='MOXA Nport 5630 16 Port Switch' LIMIT 1),NOW(),NOW()),
('EA001','EVA-214 VGA EXTENDER',NULL,'V35000MK00090',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='EVA-214 VGA EXTENDER' LIMIT 1),NOW(),NOW()),
('EA002','EVA-214 VGA EXTENDER',NULL,'V37000MK00090',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='EVA-214 VGA EXTENDER' LIMIT 1),NOW(),NOW()),
('EA003','EVA-214 VGA EXTENDER',NULL,'V35000MK00081',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='EVA-214 VGA EXTENDER' LIMIT 1),NOW(),NOW()),
('EA004','EVA-214 VGA EXTENDER',NULL,'V37000MK00081',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='EVA-214 VGA EXTENDER' LIMIT 1),NOW(),NOW()),
('HL001','HOLLYLAND MARS T1000',NULL,'022251T1012159',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='HOLLYLAND MARS T1000' LIMIT 1),NOW(),NOW()),
('HL002','HOLLYLAND MARS T1000',NULL,'022251T101215A',2023,'baik',(SELECT `id` FROM `categories` WHERE `name`='HOLLYLAND MARS T1000' LIMIT 1),NOW(),NOW()),
('AP001','APUTURE AMARAN TRI-8C V-MOUNT',NULL,'6BH00P88582',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='APUTURE AMARAN TRI-8C V-MOUNT' LIMIT 1),NOW(),NOW()),
('DC001','DCK KDJF22 Reciprocating Saw',NULL,'612309003305',2024,'baik',(SELECT `id` FROM `categories` WHERE `name`='DCK KDJF22 Reciprocating Saw' LIMIT 1),NOW(),NOW()),
('TL001','Lensa CANON HDTV Zoom Lens 40X',NULL,'0032T763',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Lensa CANON HDTV Zoom Lens 40X' LIMIT 1),NOW(),NOW()),
('MS001','Marshall CV506 HD Cam',NULL,'15520501CD0582',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Marshall CV506 HD Cam' LIMIT 1),NOW(),NOW()),
('SH001','SDI to HDMI Converter',NULL,'160800000000000992',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='SDI to HDMI Converter' LIMIT 1),NOW(),NOW()),
('KR001','KRAMER VM-5HD 3G HD-SDI DA',NULL,'09121166500068',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='KRAMER VM-5HD 3G HD-SDI DA' LIMIT 1),NOW(),NOW()),
('FL001','FLUKE 117 TRUE RMS MULTIMETER',NULL,'-',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='FLUKE 117 TRUE RMS MULTIMETER' LIMIT 1),NOW(),NOW()),
('TL002','Lensa CANON HDTV Zoom Lens 40X',NULL,'00610046',NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='Lensa CANON HDTV Zoom Lens 40X' LIMIT 1),NOW(),NOW()),
('OPT001','OPTIC CABLE 300M - KUNING',NULL,NULL,NULL,'baik',(SELECT `id` FROM `categories` WHERE `name`='OPTIC CABLE 300M - KUNING' LIMIT 1),NOW(),NOW())
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`), `details`=VALUES(`details`), `serial_number`=VALUES(`serial_number`), `procurement_year`=VALUES(`procurement_year`), `condition`=VALUES(`condition`), `category_id`=VALUES(`category_id`), `updated_at`=VALUES(`updated_at`);
/* Items upsert end */

COMMIT;